### ISSUE TITLE
Program crashed after starting

### ISSUE THREAD

**Issue by TomerGamerTV** [omkarcloud/outlook-account-generator#1]
Got this error
I'm on mac

```
python3 main.py
Task Started
[INFO] Downloading Chrome Driver in build/ directory. This is a one-time process. Download in progress...
WARNING:root:Can not find chromedriver for currently installed chrome version.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'build/115/chromedriver' -> 'build/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tomer/Downloads/outlook-account-generator/main.py", line 5, in <module>
    launch_tasks(*tasks_to_be_run)
  File "/opt/homebrew/lib/python3.11/site-packages/bose/launch_tasks.py", line 54, in launch_tasks
    current_output = task.begin_task(current_data, task_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bose/base_task.py", line 237, in begin_task
    final = run_task(False, 0)
            ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/bose/base_task.py", line 178, in run_task
    create_directories(self.task_path)
  File "/opt/homebrew/lib/python3.11/site-packages/bose/base_task.py", line 123, in create_directories
    _download_driver()
  File "/opt/homebrew/lib/python3.11/site-packages/bose/base_task.py", line 34, in _download_driver
    download_driver()
  File "/opt/homebrew/lib/python3.11/site-packages/bose/download_driver.py", line 46, in download_driver
    move_driver()
  File "/opt/homebrew/lib/python3.11/site-packages/bose/download_driver.py", line 39, in move_driver
    move_chromedriver()
  File "/opt/homebrew/lib/python3.11/site-packages/bose/download_driver.py", line 38, in move_chromedriver
    shutil.move(src_path, dest_path)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'build/115/chromedriver'
```

**Comment by Chetan11-dev** [comment]
@TomerGamerTV, 
Temporary Bug due on of the dependency of Bose chromedriver-autoinstaller. The fix is to:
1. Go to https://googlechromelabs.github.io/chrome-for-testing/#stable and download your version
2. Place it in build/ folder
3. Run python main.py and program should run successfuly.
