### ISSUE TITLE
Stop after adding the Password

### ISSUE THREAD

**Issue by shuskry** [omkarcloud/outlook-account-generator#11]
Hi, 

I'm trying to use the generator but after adding the password in the field , nothing happens ..

This is what I get in the consol :

Microsoft Windows [version 10.0.19045.3448]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\shuuj\Desktop\outlook-account-generator-master\outlook-account-generator-master>python main.py
Task Started
[INFO] Downloading Driver for Chrome Version 116 in build/ directory. This is a one-time process. Download in progress...
C:\Users\shuuj\Desktop\outlook-account-generator-master\outlook-account-generator-master\build\116\chromedriver.exe
Creating Driver with window_size=1366,768 and user_agent=REAL

DevTools listening on ws://127.0.0.1:64902/devtools/browser/0ec00e9d-7ca7-4db6-ab66-5f1c14cb06e1
Launched Browser
Sleeping for 6.000852598285325 seconds...
Sleeping for 2.3233383403057832 seconds...
Sleeping for 7.785725962370092 seconds...
Traceback (most recent call last):
  File "C:\Users\shuuj\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\base_task.py", line 190, in run_task
    result = self.run(driver, data)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuuj\Desktop\outlook-account-generator-master\outlook-account-generator-master\src\outlook_sign_up_task.py", line 154, in run
    sign_up()
  File "C:\Users\shuuj\Desktop\outlook-account-generator-master\outlook-account-generator-master\src\outlook_sign_up_task.py", line 73, in sign_up
    press_next_btn()
  File "C:\Users\shuuj\Desktop\outlook-account-generator-master\outlook-account-generator-master\src\outlook_sign_up_task.py", line 47, in press_next_btn
    driver.get_element_by_id('iSignupAction', Wait.LONG).click()
  File "C:\Users\shuuj\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 88, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\shuuj\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuuj\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\shuuj\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input type="submit" id="iSignupAction" onclick="OnNext(); return false;" class="btn btn-block win-button btn-primary" data-bind="attr: { disabled: buttons.nextButton.disabled() }, visible: buttons.nextButton.visible(), value: nextButtonText, hasFocus: buttons.nextButton.focused()" value="Suivant"> is not clickable at point (788, 658). Other element would receive the click: <div id="footer" class="footer
            default" role="contentinfo">...</div>
  (Session info: chrome=116.0.5845.188)
Stacktrace:
        GetHandleVerifier [0x012137C3+48947]
        (No symbol) [0x011A8551]
        (No symbol) [0x010AC92D]
        (No symbol) [0x010DE276]
        (No symbol) [0x010DCF4D]
        (No symbol) [0x010DB74B]
        (No symbol) [0x010DABA5]
        (No symbol) [0x010D3420]
        (No symbol) [0x010F508C]
        (No symbol) [0x010D2EB6]
        (No symbol) [0x010F53E4]
        (No symbol) [0x011075DA]
        (No symbol) [0x010F4E86]
        (No symbol) [0x010D16C7]
        (No symbol) [0x010D284D]
        GetHandleVerifier [0x0145FDF9+2458985]
        GetHandleVerifier [0x014A744F+2751423]
        GetHandleVerifier [0x014A1361+2726609]
        GetHandleVerifier [0x01290680+560624]
        (No symbol) [0x011B238C]
        (No symbol) [0x011AE268]
        (No symbol) [0x011AE392]
        (No symbol) [0x011A10B7]
        BaseThreadInitThunk [0x7545FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77427B1E+286]
        RtlGetAppContainerNamedObjectPath [0x77427AEE+238]

Press Enter To Close Browser

**Comment by shuskry** [comment]
> Hi,
> 
> I'm trying to use the generator but after resolving the capthca , nothing happens ..
> 
> This is what I get in the consol :
> 
General Rules of Captcha Solving
 - Solve it Fast
 - If you are using Residential IP AND Microsoft Captcha is too Tough. Solve via Audio Captcha.
Press fill in the captcha, the faster the less detectable, then press enter to continue ...
Traceback (most recent call last):
  File "C:\Users\shuuj\AppData\Local\Programs\Python\Python311\Lib\site-packages\bose\base_task.py", line 190, in run_task
    result = self.run(driver, data)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\shuuj\Desktop\outlook-account-generator-master\outlook-account-generator-master\src\outlook_sign_up_task.py", line 154, in run
    sign_up()
  File "C:\Users\shuuj\Desktop\outlook-account-generator-master\outlook-account-generator-master\src\outlook_sign_up_task.py", line 139, in sign_up
    yes_button.click()
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'click'
Press Enter To Close Browser

**Comment by Chetan11-dev** [comment]
Released a fix, Please follow these Steps. 

1️⃣ **Clone the Magic 🧙‍♀:**
   ```shell
   git clone https://github.com/omkarcloud/outlook-account-generator
   cd outlook-account-generator
   ```
2️⃣ **Install Dependencies 📦:**
   ```shell
   python -m pip install -r requirements.txt
   ```
3️⃣ **Let the Rain of Outlook Accounts Begin 😎:**
   ```shell
   python main.py
   ```
   
And Run the following command to update packages:

```
python -m pip install botasaurus --upgrade
```
If it occurs again please share `error_log` folder.
