### ISSUE TITLE
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input id="iSignupAction" class="btn btn-block win-button btn-primary" type="submit"> is not clickable at point (762,571) because another element <div id="footer" class="footer             default"> obscures it

### ISSUE THREAD

**Issue by azoumed** [omkarcloud/outlook-account-generator#12]
Traceback (most recent call last):
  File "C:\Users\admin\OneDrive\Bureau\messagerie\automat_gmail\outlook-account-generator-master\src\outlook\create_accounts.py", line 137, in create_accounts
    rst = sign_up()
          ^^^^^^^^^
  File "C:\Users\admin\OneDrive\Bureau\messagerie\automat_gmail\outlook-account-generator-master\src\outlook\create_accounts.py", line 92, in sign_up
    press_next_btn(driver)
  File "C:\Users\admin\OneDrive\Bureau\messagerie\automat_gmail\outlook-account-generator-master\src\outlook\create_accounts_utils.py", line 90, in press_next_btn
    lisa_click(driver, element)
  File "C:\Users\admin\OneDrive\Bureau\messagerie\automat_gmail\outlook-account-generator-master\src\outlook\create_accounts_utils.py", line 81, in lisa_click
    element.click()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 88, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <input id="iSignupAction" class="btn btn-block win-button btn-primary" type="submit"> is not clickable at point (762,571) because another element <div id="footer" class="footer
            default"> obscures it
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5
ElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:333:5
webdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:176:11
interaction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:135:11
clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:204:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:84:31

**Comment by Chetan11-dev** [comment]
Fixed,  Run the following command to update packages:

```
python -m pip install botasaurus --upgrade
```
