### ISSUE TITLE
No module named 'distutils'

### ISSUE THREAD

**Issue by ridwannsapp11** [omkarcloud/outlook-account-generator#13]
C:\Users\intel\Downloads\New folder\outlook-account-generator-master\outlook-account-generator-master>python main.py
Traceback (most recent call last):
  File "C:\Users\intel\Downloads\New folder\outlook-account-generator-master\outlook-account-generator-master\main.py", line 1, in <module>
    from bose.launch_tasks import launch_tasks
  File "C:\Users\intel\AppData\Local\Programs\Python\Python312\Lib\site-packages\bose\__init__.py", line 2, in <module>
    from .base_task import BaseTask
  File "C:\Users\intel\AppData\Local\Programs\Python\Python312\Lib\site-packages\bose\base_task.py", line 3, in <module>
    from joblib import Parallel, delayed
  File "C:\Users\intel\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "C:\Users\intel\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\memory.py", line 32, in <module>
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "C:\Users\intel\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\_store_backends.py", line 15, in <module>
    from .backports import concurrency_safe_rename
  File "C:\Users\intel\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\backports.py", line 22, in <module>
    import distutils  # noqa
    ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'distutils'

**Comment by Chetan11-dev** [comment]
Released a fix, Please follow these Steps. 

1️⃣ **Clone the Magic 🧙‍♀:**
   ```shell
   git clone https://github.com/omkarcloud/outlook-account-generator
   cd outlook-account-generator
   ```
2️⃣ **Install Dependencies 📦:**
   ```shell
   python -m pip install -r requirements.txt
   ```
3️⃣ **Let the Rain of Outlook Accounts Begin 😎:**
   ```shell
   python main.py
   ```
   
And Run the following command to update packages:

```
python -m pip install botasaurus --upgrade
```
