### ISSUE TITLE
Failed to open Firefox

### ISSUE THREAD

**Issue by ahirsr** [omkarcloud/outlook-account-generator#20]
Traceback (most recent call last):
  File "C:\Users\ahirs\Downloads\Compressed\outlook-account-generator-master\outlook-account-generator-master\src\outlook\create_accounts_utils.py", line 224, in create_firefox
    driver = AntiDetectFirefoxDriver(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahirs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\firefox\webdriver.py", line 177, in __init__
    super().__init__(
  File "C:\Users\ahirs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 272, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\ahirs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 364, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahirs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\ahirs\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0

Failed to open Firefox. Retrying...

**Comment by ahirsr** [comment]
![Screenshot 2023-12-11 010314](https://github.com/omkarcloud/outlook-account-generator/assets/153189986/c1ef5165-5809-48ca-92af-aed052b6b36d)
facing issue in windows

**Comment by Chetan11-dev** [comment]
Does it occur sometimes or every time?

**Comment by ahirsr** [comment]
every time.

**Comment by Chetan11-dev** [comment]
Trying it on another PC is your only option? The error is due to webdriver-manager, because their firefox implementation is buggy

**Comment by ahirsr** [comment]
can use in crome brower ? if yes how?

**Comment by Chetan11-dev** [comment]
No, it gets blocked
