### ISSUE TITLE
cant run the bot

### ISSUE THREAD

**Issue by 229amini** [omkarcloud/outlook-account-generator#34]
Hello Im getting this error while Im going to run main.py

Traceback (most recent call last):
  File "C:\Users\Ariad It\AppData\Local\Programs\Python\Python312\Lib\site-packages\botasaurus\decorators.py", line 369, in run_task
    result = func(driver, data)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariad It\Desktop\outlook-account-generator-master\src\outlook\create_accounts.py", line 68, in create_accounts
    account = create_user(proxy)
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ariad It\Desktop\outlook-account-generator-master\src\outlook\create_accounts_utils.py", line 374, in create_user
    country_code = find_ip_details(proxy=proxy)['country']
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by Chetan11-dev** [comment]
Try again.
