### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EsinShadrach** [omkarcloud/outlook-account-generator#4]
I'm getting this error when i run main.py

```bash
(env) rafe@shadrach:~/codes/git codes/outlook-account-generator$ python main.py
Task Started
[INFO] Downloading Driver for Chrome Version 115 in build/ directory. This is a one-time process. Download in progress...
WARNING:root:Can not find chromedriver for currently installed chrome version.
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'build/115/chromedriver' -> 'build/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rafe/codes/git codes/outlook-account-generator/main.py", line 5, in <module>
    launch_tasks(*tasks_to_be_run)
  File "/home/rafe/codes/git codes/outlook-account-generator/env/lib/python3.10/site-packages/bose/launch_tasks.py", line 54, in launch_tasks
    current_output = task.begin_task(current_data, task_config)
  File "/home/rafe/codes/git codes/outlook-account-generator/env/lib/python3.10/site-packages/bose/base_task.py", line 214, in begin_task
    final = run_task(False, 0)
  File "/home/rafe/codes/git codes/outlook-account-generator/env/lib/python3.10/site-packages/bose/base_task.py", line 155, in run_task
    create_directories(self.task_path)
  File "/home/rafe/codes/git codes/outlook-account-generator/env/lib/python3.10/site-packages/bose/base_task.py", line 99, in create_directories
    _download_driver()
  File "/home/rafe/codes/git codes/outlook-account-generator/env/lib/python3.10/site-packages/bose/base_task.py", line 34, in _download_driver
    download_driver()
  File "/home/rafe/codes/git codes/outlook-account-generator/env/lib/python3.10/site-packages/bose/download_driver.py", line 50, in download_driver
    move_driver()
  File "/home/rafe/codes/git codes/outlook-account-generator/env/lib/python3.10/site-packages/bose/download_driver.py", line 39, in move_driver
    move_chromedriver()
  File "/home/rafe/codes/git codes/outlook-account-generator/env/lib/python3.10/site-packages/bose/download_driver.py", line 38, in move_chromedriver
    shutil.move(src_path, dest_path)
  File "/usr/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'build/115/chromedriver'
```

**Comment by Chetan11-dev** [comment]
This is a Temporary Bug due which occurs in Chrome 115 due to `chromedriver-autoinstaller`  dependency. The fix is to:

1. Go to [https://googlechromelabs.github.io/chrome-for-testing/#stable](https://googlechromelabs.github.io/chrome-for-testing/#stable) and download "chrome driver" based on your chrome version. (Most likely 115)
2. Extract the zip file
3. Place the "chromedriver" file (or "chromedriver.exe" if you are using Windows) directly into the build/ folder. Make sure you're not placing the extracted folder but only the chrome driver file itself.
    
    ![Screenshot (520).png](https://chetan-jain-omkar.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Ff7ddfb18-ad8e-492c-83a2-1b2e65faeda2%2FScreenshot_(520).png?table=block&id=de77211e-a7da-4149-ad02-33338569af27&spaceId=8fb8cd62-9b0a-4bc4-bdb3-dc442b11cf8a&width=920&userId=&cache=v2)
    
4. Run `python main.py` and program should run successfully.
