### ISSUE TITLE
no module named packing

### ISSUE THREAD

**Issue by XaiMTM** [omkarcloud/outlook-account-generator#7]
D:\outlook-account-generator-master>python main.py
Task Started
Traceback (most recent call last):
  File "D:\outlook-account-generator-master\main.py", line 5, in <module>
    launch_tasks(*tasks_to_be_run)
  File "C:\Users\Xai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\launch_tasks.py", line 54, in launch_tasks
    current_output = task.begin_task(current_data, task_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 219, in begin_task
    final = run_task(False, 0)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 160, in run_task
    create_directories(self.task_path)
  File "C:\Users\Xai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 104, in create_directories
    _download_driver()
  File "C:\Users\Xai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\base_task.py", line 33, in _download_driver
    from .download_driver import download_driver
  File "C:\Users\Xai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\bose\download_driver.py", line 1, in <module>
    import chromedriver_autoinstaller_fix
  File "C:\Users\Xai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromedriver_autoinstaller_fix\__init__.py", line 7, in <module>
    from . import utils
  File "C:\Users\Xai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\chromedriver_autoinstaller_fix\utils.py", line 19, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

**Comment by pacokeks** [comment]
you need to install the "packaging" paket via pip or pycharm

**Comment by XaiMTM** [comment]
how to install it?

**Comment by XaiMTM** [comment]
it worked
